### PR TITLE
Use revised icon set

### PR DESCRIPTION
**Pull request by rpanderson**
Use new art in README.md (absolute links for PyPI) and sphinx docs, and remove unused and deprecated files in `img` and `docs/source/img` folders (as docs can be built using relative links to parent folders).

Also fixed errant link in prelude text (analysis verb should link to labscript-suite/lyse).

### CODE REVIEW

**Comment by rpanderson** [comment]
Damn, looks like the assets outside of the doc source aren't included on Read the Docs, whereas they work when building the docs locally:
image

**Comment by philipstarkey** [comment]
You spelt transparent wrong in the file path 🙂

**Comment by rpanderson** [comment]
Yeah I noticed :-P Fixing now.

**Comment by philipstarkey** [comment]
The filenames were spelt wrong too, but @chrisjbillington fixed it in d9cb5713eba39543cf56ae7fa7caf7870a4ad4d2. You must have been working from the old revision and pulled in the new changes as part of your post merge workflow!

**Pull request merged**
