### PR TITLE
Add subdirectory for art: logos, application icons etc.

### PR DESCRIPTION
**Pull request by chrisjbillington**
Main source is art/source/labscript-suite-icons.svg. It now contains
icons optimised for 16x16, 22x22 and 32x32 resolution, so blurry icons
should be a thing of the past.

This is an inkscape svg with defined grids and rulers and whatnot so
if you're going to edit it, use inkscape.

Banner logos also recreated in this source svg.

Icons and logos are exported at native resolutions and a few multiples
thereof in png, ico and svg form. Any logos you need should be here.

Following Russ's lead, runviewer's icon has red text now.

Make the blue and red we use a bit darker.

This PR is partly motivated by seeing icons that are not rendered correctly floating around - wrong linewidths etc. These resources should mean people should have more of what they need for docs and websites without having to export more svgs.

I think it makes more sense to keep all this in once place instead of the individual projects, since it's pretty coupled. Will get newly-optimised .icos and other icons into the applications in due course.

### CODE REVIEW

**Comment by chrisjbillington** [comment]
I didn't delete the iconds in the 'img' directory because I don't know what is linking to them. But I suggest icons from this directory are linked to instead and then the others deleted.

**Comment by chrisjbillington** [comment]
Annoying that github doesn't show the images in the images tab, but apparently I can just drag and drop every png into this comment so here we go:

lyse_16x16
lyse_22x22
lyse_32x32
lyse_64x64
lyse_128x128
lyse_256x256

--------

blacs_16x16
blacs_22x22
blacs_32x32
blacs_64x64
blacs_128x128
blacs_256x256

--------

labscript_16x16 png
labscript_22x22
labscript_32x32
labscript_64x64
labscript_128x128
labscript_256x256

--------

runviewer_16x16
runviewer_22x22
runviewer_32x32
runviewer_64x64
runviewer_128x128
runviewer_256x256

--------

runmanager_16x16
runmanager_22x22
runmanager_32x32
runmanager_64x64
runmanager_128x128
runmanager_256x256

--------

labscript-banner_32
labscript-banner_64
labscript-banner_128
labscript-banner_256

--------

labscript-suite-square-dark_138
labscript-suite-square-dark_276
labscript-suite-square-dark_552

--------

labscript-suite-square-white_138
labscript-suite-square-white_276
labscript-suite-square-white_552

--------

labscript-suite-rectangular-white_70
labscript-suite-rectangular-white_140
labscript-suite-rectangular-white_280

--------

labscript-suite-rectangular-transparant_70
labscript-suite-rectangular-transparant_140
labscript-suite-rectangular-transparant_280

**Comment by philipstarkey** [comment]
What version of Inkscape did you use? (Just for reference. They changed the default DPI a few years ago and I've been wary since!)

**Comment by chrisjbillington** [comment]
Inkscape 1.0. Default dpi seems to be 96, and I have noticed that I get prompted whenever I open old files to tell it whether they are for screen display or printing. I guess changing the default dpi explains why it asks that! It's asking whether to keep phyical measurements or pixels true to what the document says, since it can't do both if the DPI is changing!

**Comment by philipstarkey** [comment]
Cool! It changed in 0.92, and almost completely ruined my thesis figures. I ended up ensuring I installed the same old version I was originally using on every PC I used for my thesis. (I should probably upgrade now). Hopefully now that they've reached 1.0 they won't make such drastic changes in the future.

**Comment by chrisjbillington** [comment]
> It changed in 0.92, and almost completely ruined my thesis figures.

Yikes! I don't remember facing the same issue, but I think I probably didn't use inkscape much for thesis figures.

> Hopefully now that they've reached 1.0 they won't make such drastic changes in the future.
I would imagine so

**Comment by rpanderson** [comment]
This is great!

**Comment by rpanderson** [comment]
What resolution are the .ico files? (Sorry, I'm on mobile.) The html_favicon in sphinx apparently requires 16x16 or 32x32 .ico files.

**Comment by chrisjbillington** [comment]
The .ico files contain all the other resolutions. So long as sphinx is capable of getting the one it wants out rather than just say, using the first listed, it should be fine. Might just have to test to find out!

**Comment by rpanderson** [comment]
> Might just have to test to find out!
Works just fine; and looks a damn sight better, too.
image

Typo: transparant

**Comment by rpanderson** [comment]
blacs_128x128.png: The border extends to the image bounds.

**Comment by chrisjbillington** [comment]
> blacs_128x128.png: The border extends to the image bounds.

That's intentional and is the case for all the icons - only the suite logos have padding. Is it a problem? (or am I misunderstanding?)

**Comment by rpanderson** [comment]
False alarm. It's a glitch with my file browser:

image

**Pull request merged**
